/**
 * Job Notification Tracker — 60 realistic Indian tech jobs
 */

export const JOBS = [
  {
    id: "j1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/example-1",
    description: "Join Amazon's engineering team for a 6-month internship. You will work on real projects alongside experienced engineers, contribute to production code, and learn best practices at scale."
  },
  {
    id: "j2",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot", "Angular"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.tcs.com/careers/job-details",
    description: "TCS GET program offers comprehensive training in enterprise technologies. You will be placed in projects across banking, retail, or healthcare domains after a 3-month induction."
  },
  {
    id: "j3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/jobs/backend-junior",
    description: "Build scalable payment infrastructure at Razorpay. You will work on APIs handling millions of transactions, integrate with banks, and ensure data integrity."
  },
  {
    id: "j4",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.freshworks.com/company/careers",
    description: "Work on Freshworks product UI. You will build reusable components, improve UX, and collaborate with designers on customer-facing features."
  },
  {
    id: "j5",
    title: "QA Intern",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Selenium", "Manual Testing", "JIRA", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.infosys.com/careers",
    description: "Learn quality assurance practices at Infosys. You will write test cases, automate regression suites, and work with agile teams on enterprise projects."
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/",
    description: "Analyze delivery data, order patterns, and customer behaviour. You will create dashboards and reports that drive business decisions for India's largest food delivery platform."
  },
  {
    id: "j7",
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.capgemini.com/careers",
    description: "Join Capgemini's Java practice. You will develop enterprise applications, integrate with legacy systems, and work on client projects in BFSI or manufacturing."
  },
  {
    id: "j8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.zoho.com/careers",
    description: "Build products at Zoho. You will work on Zoho's suite of business apps, write clean Python code, and contribute to a bootstrapped product company."
  },
  {
    id: "j9",
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.phonepe.com/careers",
    description: "Build the frontend for India's largest payments app. You will create responsive UPI flows, optimise performance, and ensure millions of users have a smooth experience."
  },
  {
    id: "j10",
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Kotlin", "Android", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/",
    description: "Intern with Flipkart's mobile team. You will work on the Android app, improve checkout flow, and learn e-commerce tech at scale."
  },
  {
    id: "j11",
    title: "Graduate Engineer Trainee",
    company: "Wipro",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: [".NET", "C#", "SQL Server", "Azure"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.wipro.com/",
    description: "Wipro GET program trains you in Microsoft technologies. After induction, you will join projects in cloud, digital, or enterprise solutions."
  },
  {
    id: "j12",
    title: "Backend Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Go", "PostgreSQL", "Kafka", "Redis"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://juspay.io/careers",
    description: "Build payment orchestration at Juspay. You will work on high-throughput systems that power payments for Uber, Swiggy, and other partners."
  },
  {
    id: "j13",
    title: "Full Stack Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://cred.club/careers",
    description: "Work on CRED's credit card rewards platform. You will build features for members, integrate with banks, and learn fintech product development."
  },
  {
    id: "j14",
    title: "Java Developer (0-1)",
    company: "Accenture",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Kafka", "Docker"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers",
    description: "Join Accenture's technology practice. You will develop microservices, work with cloud platforms, and deliver solutions for Fortune 500 clients."
  },
  {
    id: "j15",
    title: "Frontend Developer (1-3)",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "Webpack"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.postman.com/company/careers",
    description: "Build the Postman web app. You will create interfaces for API development, collaborate with product, and improve the developer experience."
  },
  {
    id: "j16",
    title: "Data Analyst Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "SQL", "Pandas", "Power BI"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://paytm.com/careers",
    description: "Analyze fintech data at Paytm. You will work on payments, lending, and merchant analytics to uncover insights for product and business teams."
  },
  {
    id: "j17",
    title: "DevOps Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "Linux"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.ibm.com/in-en/careers",
    description: "Learn cloud and DevOps at IBM. You will set up CI/CD pipelines, manage cloud infrastructure, and support enterprise deployments."
  },
  {
    id: "j18",
    title: "Android Developer (0-1)",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Kotlin", "Android SDK", "Jetpack", "MVVM"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://unacademy.com/careers",
    description: "Build the Unacademy learning app. You will work on live classes, offline playback, and features that help millions of learners study effectively."
  },
  {
    id: "j19",
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C#", "Azure", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.microsoft.com/",
    description: "Intern with Microsoft India. You will work on Azure, Office, or Windows products and learn engineering practices at a global tech leader."
  },
  {
    id: "j20",
    title: "Backend Developer (1-3)",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "Redis", "Elasticsearch"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://sharechat.com/careers",
    description: "Build backend for India's regional social platform. You will work on feeds, content moderation, and systems serving millions of daily active users."
  },
  {
    id: "j21",
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "AWS", "Agile"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.cognizant.com/in/en/careers",
    description: "Cognizant's GET program prepares you for IT consulting. You will receive training and then join projects in healthcare, finance, or retail."
  },
  {
    id: "j22",
    title: "Python Developer (Fresher)",
    company: "HackerRank",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.hackerrank.com/careers",
    description: "Build the HackerRank platform. You will work on code execution, assessment features, and tools that help companies hire developers."
  },
  {
    id: "j23",
    title: "QA Engineer (0-1)",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "Appium", "API Testing", "JIRA"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.olacabs.com/careers",
    description: "Ensure quality for Ola's ride-hailing app. You will write automated tests, perform regression, and work with mobile and backend teams."
  },
  {
    id: "j24",
    title: "Frontend Intern",
    company: "Dukaan",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "Next.js", "Tailwind", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://dukaan.app/careers",
    description: "Build the Dukaan storefront. You will create seller dashboards, optimise for mobile, and help small businesses go online."
  },
  {
    id: "j25",
    title: "Java Developer (1-3)",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Oracle DB", "PL/SQL", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.oracle.com/in/corporate/careers",
    description: "Work on Oracle Cloud applications. You will develop enterprise software, integrate with Oracle databases, and support cloud migrations."
  },
  {
    id: "j26",
    title: "Data Engineer Intern",
    company: "Myntra",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Spark", "SQL", "Airflow"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.myntra.com/careers",
    description: "Build data pipelines at Myntra. You will work on ETL, warehouse models, and analytics that power India's leading fashion e-commerce platform."
  },
  {
    id: "j27",
    title: "React Developer (Fresher)",
    company: "BharatPe",
    location: "Delhi NCR",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "Redux", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "4–6 LPA",
    applyUrl: "https://bharatpe.com/careers",
    description: "Build merchant-facing apps at BharatPe. You will create UIs for QR payments, lending, and tools that help small businesses grow."
  },
  {
    id: "j28",
    title: "SDE Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Linux", "Networking"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jobs.dell.com/",
    description: "Intern with Dell's India R&D. You will work on storage, networking, or server products and learn enterprise hardware-software integration."
  },
  {
    id: "j29",
    title: "Backend Developer (0-1)",
    company: "Instamojo",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Stripe"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.instamojo.com/careers",
    description: "Build payment APIs at Instamojo. You will work on checkout, refunds, and integrations that help SMEs accept online payments."
  },
  {
    id: "j30",
    title: "iOS Developer (1-3)",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Swift", "iOS SDK", "UIKit", "Core Data"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.nykaa.com/careers",
    description: "Build the Nykaa app. You will work on beauty and fashion features, improve performance, and enhance the shopping experience for millions of users."
  },
  {
    id: "j31",
    title: "Graduate Engineer Trainee",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SAP ABAP", "SQL", "Fiori"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "5–7 LPA",
    applyUrl: "https://www.sap.com/india/about/careers.html",
    description: "Join SAP Labs India. You will learn SAP technologies, contribute to ERP modules, and work on solutions for global enterprises."
  },
  {
    id: "j32",
    title: "Full Stack Intern",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Node.js", "React", "MongoDB", "Redis"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://clevertap.com/careers",
    description: "Build the CleverTap engagement platform. You will work on dashboards, analytics, and features that help brands retain customers."
  },
  {
    id: "j33",
    title: "DevOps Engineer (0-1)",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Docker", "Kubernetes", "Terraform", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://innovaccer.com/careers",
    description: "Manage cloud infrastructure for healthcare tech. You will set up CI/CD, monitor systems, and ensure HIPAA-compliant deployments."
  },
  {
    id: "j34",
    title: "Machine Learning Intern",
    company: "Walmart Global Tech",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "TensorFlow", "SQL", "ML Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.walmart.com/",
    description: "Work on ML models at Walmart India. You will build recommendation systems, demand forecasting, or computer vision for retail."
  },
  {
    id: "j35",
    title: "Java Developer (Fresher)",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Spring", "TDD", "Clean Code"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.thoughtworks.com/careers",
    description: "Join Thoughtworks as a graduate developer. You will pair program, write tests, and deliver software using agile practices."
  },
  {
    id: "j36",
    title: "Frontend Developer (0-1)",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "PWA", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://meesho.com/careers",
    description: "Build the Meesho reseller app. You will create responsive UIs, optimise for low-end devices, and help millions discover products."
  },
  {
    id: "j37",
    title: "SDE Intern",
    company: "Google",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "Distributed Systems"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.google.com/",
    description: "Intern with Google India. You will work on Search, Ads, or Cloud and learn engineering at one of the world's leading tech companies."
  },
  {
    id: "j38",
    title: "Backend Intern",
    company: "Groww",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Node.js", "PostgreSQL", "Redis", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://groww.in/careers",
    description: "Build fintech backend at Groww. You will work on investments, mutual funds, and systems that help Indians invest smarter."
  },
  {
    id: "j39",
    title: "QA Intern",
    company: "Cvent",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "SQL", "Agile"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.cvent.com/en/careers",
    description: "Test Cvent's event tech platform. You will write test cases, automate flows, and ensure quality for the world's leading event management software."
  },
  {
    id: "j40",
    title: "Python Developer (1-3)",
    company: "Practo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "Celery", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.practo.com/careers",
    description: "Build healthcare tech at Practo. You will work on doctor discovery, appointment booking, and systems connecting patients with healthcare providers."
  },
  {
    id: "j41",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Angular", "SQL", "DevOps"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.lntinfotech.com/careers",
    description: "Join LTI's graduate program. You will receive training and work on digital transformation projects for global clients."
  },
  {
    id: "j42",
    title: "React Developer (0-1)",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "Redux", "JavaScript", "Responsive Design"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "5–8 LPA",
    applyUrl: "https://careers.makemytrip.com/",
    description: "Build the MakeMyTrip web app. You will work on flight, hotel, and bus booking flows for India's largest travel platform."
  },
  {
    id: "j43",
    title: "Data Analyst Intern",
    company: "Policybazaar",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Excel", "SQL", "Python", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.policybazaar.com/careers",
    description: "Analyse insurance data at Policybazaar. You will create reports, build dashboards, and support product decisions for India's largest insurance aggregator."
  },
  {
    id: "j44",
    title: "Backend Developer (1-3)",
    company: "Delhivery",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Kafka", "PostgreSQL", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.delhivery.com/careers",
    description: "Build logistics tech at Delhivery. You will work on tracking, routing, and systems that power India's largest logistics network."
  },
  {
    id: "j45",
    title: "SDE Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "JavaScript", "Algorithms", "Web Technologies"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.adobe.com/",
    description: "Intern with Adobe India. You will work on Creative Cloud, Document Cloud, or Experience Cloud products used by millions globally."
  },
  {
    id: "j46",
    title: "Java Developer (0-1)",
    company: "Mindtree",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "REST", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.mindtree.com/careers",
    description: "Join Mindtree's Java practice. You will develop enterprise applications and work on digital transformation projects for global clients."
  },
  {
    id: "j47",
    title: "Frontend Intern",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.inmobi.com/company/careers",
    description: "Build ad tech interfaces at InMobi. You will work on publisher dashboards, reporting tools, and the world's leading independent ad platform."
  },
  {
    id: "j48",
    title: "Python Developer (0-1)",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "Celery", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/jobs/python-dev",
    description: "Build payment automation at Razorpay. You will work on reconciliation, reporting, and backend systems powering millions of transactions."
  },
  {
    id: "j49",
    title: "DevOps Intern",
    company: "HashedIn",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["AWS", "Docker", "Jenkins", "Terraform"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://hashedin.com/careers",
    description: "Learn DevOps at HashedIn. You will set up pipelines, manage cloud resources, and support deployments for SaaS products."
  },
  {
    id: "j50",
    title: "Full Stack Developer (1-3)",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["Node.js", "React", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.browserstack.com/careers",
    description: "Build the BrowserStack platform. You will work on real device cloud, API infrastructure, and tools used by developers worldwide."
  },
  {
    id: "j51",
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SAP", "Testing", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.techmahindra.com/careers",
    description: "Join Tech Mahindra's graduate program. You will receive training in emerging technologies and work on telecom or enterprise projects."
  },
  {
    id: "j52",
    title: "Backend Intern",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.dunzo.com/careers",
    description: "Build hyperlocal delivery tech at Dunzo. You will work on order management, routing, and systems for quick commerce."
  },
  {
    id: "j53",
    title: "React Developer (1-3)",
    company: "Livspace",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.livspace.com/in/careers",
    description: "Build the Livspace home design platform. You will create 3D configurators, design tools, and interfaces for interior design."
  },
  {
    id: "j54",
    title: "QA Engineer (Fresher)",
    company: "Licious",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Selenium", "Postman"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.licious.in/careers",
    description: "Ensure quality for Licious apps. You will test the meat and seafood ordering flow, delivery tracking, and customer experience."
  },
  {
    id: "j55",
    title: "SDE Intern",
    company: "Intel",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C", "Python", "Linux", "Algorithms"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.intel.com/content/www/us/en/jobs.html",
    description: "Intern with Intel India. You will work on drivers, firmware, or software that powers the world's computing infrastructure."
  },
  {
    id: "j56",
    title: "Java Developer (1-3)",
    company: "HCL Tech",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring", "Microservices", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.hcltech.com/careers",
    description: "Join HCL's digital practice. You will develop cloud-native applications and work on digital transformation for enterprise clients."
  },
  {
    id: "j57",
    title: "Data Engineer Intern",
    company: "Rebel Foods",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Spark", "SQL", "Airflow"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.rebelfoods.co/careers",
    description: "Build data infrastructure for cloud kitchens. You will work on order analytics, kitchen ops data, and insights for Faasos, Behrouz, and more."
  },
  {
    id: "j58",
    title: "Frontend Developer (0-1)",
    company: "Upstox",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "TypeScript", "Redux", "WebSocket"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "5–8 LPA",
    applyUrl: "https://upstox.com/careers",
    description: "Build the Upstox trading platform. You will create real-time charts, order forms, and interfaces for millions of retail investors."
  },
  {
    id: "j59",
    title: "Python Developer (Fresher)",
    company: "Decimal Point Analytics",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Pandas", "NumPy", "SQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://decimalpointanalytics.com/careers",
    description: "Join DPA's analytics team. You will build data pipelines, create reports, and support financial analytics for global clients."
  },
  {
    id: "j60",
    title: "Backend Developer (0-1)",
    company: "ElasticRun",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.elasticrun.com/careers",
    description: "Build logistics backend at ElasticRun. You will work on last-mile delivery, inventory management, and systems for rural distribution."
  }
];
